language: ruby
rvm:
- 2.2.0
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
services:
- postgresql
os:
- linux
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
- psql -c 'create database cerebralcortex_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake test:all:db
notifications:
  slack:
    secure: jM2mpNOR8BoyZupDqZvqPGiDdVI9dxAmLPjPlEoox20vo5w4kQoMwgsGDLk+Q5/d/EW7rP2NhKmvUT9Av4VeDJnsPKCqRDdHuglmQmqNxHvjdFqwM9n/iszj2j2hw1+uaPGR0XPhdvQl1g+uA+n6OdjtQn0n+zaqKGcIhoz/JLRcWCCYmurNNwO4hwUQvurTRt7Zo0UoEAt/FumcJpv/C1IWpGUU50UYGCDChIUNeWkX6AKBUkrXLobF61O6OohdxGryyOJTOod7sPK+ZLdPo9LI4db7DllHMmLnXlLcAcsipHFaD8tC9jZE1UFemZloAQ+NqKBtJl/pylcpRvIaV8/Pntb675x/LQEgogcj0aWF4fJ+kY0kTnw4dSspP8P4g1hhcpBDZ8DQ4To3w7ZD6k0se5U0baVSfS1UbZLIEtSP1F2R1InJKIkeTgVZ4Ppy0lZGFJ087IgkZb1oSSYexvR8CncgqiJlxRgPFgXk5ui3tt8nKclWBP5iuETJjlpek7cUlqu6TdrqGtfz+oMsDkOSjyDLJFpz07qmD0DY4+lu3APsJhSMxVn3A5PcYUmyxc5MHSprRyGfIDKw/y9a7bOPEZ0xE1q6b2XFhb6G/4ukvz5JXZA4IvLsXzJDxLU0+GCP6kg78m/Xh48atbijvCz2Tfg0JwaL3PRVHvPQ6sA=
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false