development:
  hosts:
    - '127.0.0.1'
  port: 9042
  username: 'dev'
  password: 'dev'
  keyspace: cerebralcortex_dev
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  hosts:
    - '127.0.0.1'
  port: 9042
  keyspace: cerebralcortex_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - 'tatooine10dot'
    - 'alderaan10dot'
    - 'yavin10dot'
  port: 9042
  keyspace: cerebralcortex_production
  username: 'cerebralcortex'
  password: '6KWKJ1v34bZ4'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 3
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
